env: "local"

grpc:
  booking:
    port: 60008
  public:
    port: 60009

metrics:
  port: 9098

tracer:
  end-point: "localhost:4318"
  insecure: true
  sample-ratio: 1.0

database:
  host: "postgres"
  port: 5432
  user: "postgres"
  password: "postgres"
  name: "resource_service"
  ssl_mode: "disable"